POST http://localhost:3003/api/blogs/667e6ef577f8b05842d28180/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFub3RoZXIiLCJpZCI6IjY2MzA5ZTcxYWMyNjlkMjI3ZGRkZmY3YiIsImlhdCI6MTcxNDQ3MDE3NX0.tdH1FgTM7tTuNHPk9WNLWqCod_V_Oelz8TAyOX5igqc

{
  "comment": "testing comments"
}